import type { PageSectionRegistry } from '../../../engine/PageSectionRegistry'
import {
  AboutSection,
  AreasGridSection,
  BenefitsSection,
  CallToActionSection,
  ContactSection,
  FaqSection,
  HeroSection,
  LegalContentSection,
  LocalAreaIntroductionSection,
  NotFoundSection,
  ProcessStepsSection,
  QuoteRequestSection,
  RelatedLinksSection,
  ServiceDetailsSection,
  ServicesGridSection,
  TrustFeaturesSection,
} from '../sections/sections'
import {
  FoundersSection,
  HouseListSection,
  ProblemSection,
  ProofGallerySection,
  ReviewsSection,
  ServiceStandardSection,
  SolutionSection,
} from '../sections/redesignSections'

export const pageSectionRegistry: PageSectionRegistry = {
  hero: HeroSection,
  'trust-features': TrustFeaturesSection,
  'services-grid': ServicesGridSection,
  'service-details': ServiceDetailsSection,
  'process-steps': ProcessStepsSection,
  'areas-grid': AreasGridSection,
  'local-area-introduction': LocalAreaIntroductionSection,
  benefits: BenefitsSection,
  about: AboutSection,
  faq: FaqSection,
  contact: ContactSection,
  'quote-request': QuoteRequestSection,
  'call-to-action': CallToActionSection,
  'related-links': RelatedLinksSection,
  'legal-content': LegalContentSection,
  'not-found': NotFoundSection,
  problem: ProblemSection,
  solution: SolutionSection,
  'house-list': HouseListSection,
  'service-standard': ServiceStandardSection,
  founders: FoundersSection,
  'proof-gallery': ProofGallerySection,
  reviews: ReviewsSection,
}
