import { useEffect, useRef, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { hasRole } from '../../../auth/authorization'
import { useAuth } from '../../../auth/useAuth'
import { toUiError } from '../../../api/errors'
import { useCreatePayment, usePayments, useQuote, useUpdatePaymentStatus, useUpdateQuote, useUpdateQuoteStatus } from '../api/finance-hooks'
import { paymentTransitions, quoteTransitions } from '../utils/actions'
import { centsToCurrency, currencyInputToCents } from '../utils/money'
import { dateToDatetimeLocal, datetimeLocalToIso } from '../utils/datetime-local'
import type { Payment, PaymentMethod, PaymentStatus, QuoteStatus, UpdateQuoteInput } from '../types/contracts'
import { PaymentStatusBadge, QuoteStatusBadge } from './FinanceBadges'
import { methodLabels, paymentLabels, quoteLabels } from './labels'
import { QuoteForm } from './QuoteForm'

const date = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' })
const showDate = (value: string | null) => value ? date.format(new Date(value)) : 'Não informado'
function PaymentActions({ payment, quoteId }: { payment: Payment; quoteId: string }) {
  const auth = useAuth(); const mutation = useUpdatePaymentStatus(quoteId, payment.id)
  if (!hasRole(auth.user, ['ADMIN'])) return null
  async function act(status: PaymentStatus) { if ((status === 'CANCELLED' || status === 'REFUNDED') && !window.confirm(`Confirmar: ${paymentLabels[status]}?`)) return; try { await mutation.mutateAsync({ status: status as 'PAID' | 'CANCELLED' | 'REFUNDED', ...(status === 'PAID' ? { paidAt: new Date().toISOString() } : {}) }) } catch { /* mensagem segura */ } }
  return <div className="amigo-admin-dialog-actions">{paymentTransitions[payment.status].map((status) => <button key={status} disabled={mutation.isPending} onClick={() => void act(status)}>{status === 'PAID' ? 'Marcar como pago' : status === 'CANCELLED' ? 'Cancelar pagamento' : 'Registrar reembolso'}</button>)}{mutation.isError && <p role="alert">{toUiError(mutation.error).userMessage}</p>}</div>
}
function PaymentForm({ quoteId, remainingCents, onDone }: { quoteId: string; remainingCents: number; onDone: () => void }) {
  const create = useCreatePayment(quoteId); const [message, setMessage] = useState(''); const submitting = useRef(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (create.isPending || submitting.current) return; const data = new FormData(event.currentTarget); try { const amountCents = currencyInputToCents(String(data.get('amount'))); if (amountCents <= 0) throw new RangeError('O valor deve ser maior que zero.'); if (amountCents > remainingCents) throw new RangeError('O valor não pode superar o saldo informado pela API.'); const status = String(data.get('status')) as 'PENDING' | 'PAID'; submitting.current = true; await create.mutateAsync({ amountCents, method: String(data.get('method')) as PaymentMethod, status, ...(status === 'PAID' ? { paidAt: datetimeLocalToIso(String(data.get('paidAt'))) } : {}), reference: String(data.get('reference') || '').trim() || undefined, notes: String(data.get('notes') || '').trim() || undefined }); onDone() } catch (error) { if (error instanceof RangeError) setMessage(error.message) } finally { submitting.current = false } }
  return <form onSubmit={(event) => void submit(event)} aria-label="Registrar pagamento"><p>Saldo disponível: <strong>{centsToCurrency(remainingCents)}</strong></p><label>Valor (R$)<input name="amount" inputMode="decimal" required /></label><label>Método<select name="method">{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Status inicial<select name="status"><option value="PENDING">Pendente</option><option value="PAID">Pago</option></select></label><label>Data do pagamento<input name="paidAt" type="datetime-local" defaultValue={dateToDatetimeLocal(new Date())} /></label><label>Referência<input name="reference" maxLength={300} /></label><label>Observações<textarea name="notes" maxLength={4000} /></label><button disabled={create.isPending}>{create.isPending ? 'Registrando…' : 'Registrar pagamento'}</button>{message && <p role="alert">{message}</p>}{create.isError && <p role="alert">{toUiError(create.error).userMessage}</p>}<p>Nenhum número de cartão, CVV ou outro dado sensível deve ser informado.</p></form>
}
export function QuoteDetails({ id, onClose }: { id: string; onClose: () => void }) {
  const auth = useAuth(); const query = useQuote(id); const payments = usePayments(id); const update = useUpdateQuote(id); const statusMutation = useUpdateQuoteStatus(id); const closeRef = useRef<HTMLButtonElement>(null); const [editing, setEditing] = useState(false); const [paymentForm, setPaymentForm] = useState(false)
  useEffect(() => { const origin = document.activeElement as HTMLElement | null; closeRef.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape' && !update.isPending && !statusMutation.isPending) onClose() }; document.addEventListener('keydown', key); return () => { document.removeEventListener('keydown', key); origin?.focus() } }, [onClose, statusMutation.isPending, update.isPending])
  const quote = query.data; const isAdmin = hasRole(auth.user, ['ADMIN'])
  async function changeStatus(status: QuoteStatus) { if (!isAdmin) return; if ((status === 'REJECTED' || status === 'CANCELLED') && !window.confirm(`Confirmar: ${quoteLabels[status]}?`)) return; try { await statusMutation.mutateAsync({ status: status as 'SENT' | 'APPROVED' | 'REJECTED' | 'CANCELLED' }) } catch { /* mensagem abaixo */ } }
  const paymentItems = payments.data ?? []
  return <aside className="amigo-admin-drawer amigo-finance-drawer" role="dialog" aria-modal="true" aria-labelledby="quote-detail-title"><div className="amigo-admin-drawer-header"><h2 id="quote-detail-title">Detalhes do orçamento</h2><button ref={closeRef} onClick={onClose}>Fechar</button></div>{query.isPending && <p role="status">Carregando detalhes…</p>}{query.isError && <div role="alert"><p>{toUiError(query.error).userMessage}</p><button onClick={() => void query.refetch()}>Tentar novamente</button></div>}
    {quote && <><dl className="amigo-admin-details-list"><div><dt>Cliente</dt><dd>{quote.serviceRequest.customer.name}</dd></div><div><dt>Telefone</dt><dd>{quote.serviceRequest.customer.phone}</dd></div><div><dt>E-mail</dt><dd>{quote.serviceRequest.customer.email ?? 'Não informado'}</dd></div><div><dt>Serviço</dt><dd>{quote.serviceRequest.service.name}</dd></div><div><dt>Solicitação</dt><dd><Link to={`/admin/solicitacoes?request=${quote.serviceRequestId}`}>Abrir solicitação</Link></dd></div><div><dt>Status</dt><dd><QuoteStatusBadge status={quote.status} /></dd></div><div><dt>Subtotal</dt><dd>{centsToCurrency(quote.subtotalCents)}</dd></div><div><dt>Desconto</dt><dd>{centsToCurrency(quote.discountCents)}</dd></div><div><dt>Total</dt><dd>{centsToCurrency(quote.totalCents)}</dd></div><div><dt>Pago</dt><dd>{centsToCurrency(quote.paidTotalCents)}</dd></div><div><dt>Saldo</dt><dd>{centsToCurrency(quote.remainingCents)}</dd></div><div><dt>Situação financeira</dt><dd>{quote.paymentStatus}</dd></div><div><dt>Validade</dt><dd>{showDate(quote.validUntil)}</dd></div><div><dt>Descrição</dt><dd>{quote.description ?? 'Não informada'}</dd></div><div><dt>Observações</dt><dd>{quote.notes ?? 'Sem observações'}</dd></div>{quote.approvedAt && <div><dt>Aprovado em</dt><dd>{showDate(quote.approvedAt)}</dd></div>}{quote.rejectedAt && <div><dt>Rejeitado em</dt><dd>{showDate(quote.rejectedAt)}</dd></div>}{quote.cancelledAt && <div><dt>Cancelado em</dt><dd>{showDate(quote.cancelledAt)}</dd></div>}</dl>
      {quote.status === 'DRAFT' && <button onClick={() => setEditing((value) => !value)}>{editing ? 'Fechar edição' : 'Editar orçamento'}</button>}{editing && <QuoteForm quote={quote} isPending={update.isPending} error={update.error} onSubmit={async (input) => { await update.mutateAsync(input as UpdateQuoteInput); setEditing(false) }} />}
      {isAdmin && <section><h3>Alterar status</h3><div className="amigo-admin-dialog-actions">{quoteTransitions[quote.status].map((next) => <button key={next} disabled={statusMutation.isPending} onClick={() => void changeStatus(next)}>{next === 'SENT' ? 'Enviar orçamento' : next === 'APPROVED' ? 'Aprovar' : next === 'REJECTED' ? 'Rejeitar' : 'Cancelar'}</button>)}</div>{statusMutation.isError && <p role="alert">{toUiError(statusMutation.error).userMessage}</p>}</section>}
      <section><h3>Pagamentos</h3>{payments.isPending && <p role="status">Carregando pagamentos…</p>}{payments.isError && <div role="alert"><p>{toUiError(payments.error).userMessage}</p><button onClick={() => void payments.refetch()}>Tentar novamente</button></div>}{payments.isSuccess && paymentItems.length === 0 && <p>Nenhum pagamento registrado.</p>}{paymentItems.map((payment) => <article className="amigo-payment-card" key={payment.id}><h4>{centsToCurrency(payment.amountCents)} — {methodLabels[payment.method]}</h4><p><PaymentStatusBadge status={payment.status} /> · {showDate(payment.paidAt)}</p>{payment.reference && <p>Referência: {payment.reference}</p>}{payment.notes && <p>{payment.notes}</p>}<PaymentActions payment={payment} quoteId={id} /></article>)}{isAdmin && quote.status === 'APPROVED' && quote.remainingCents > 0 && <><button onClick={() => setPaymentForm((value) => !value)}>{paymentForm ? 'Fechar registro' : 'Registrar pagamento'}</button>{paymentForm && <PaymentForm quoteId={id} remainingCents={quote.remainingCents} onDone={() => setPaymentForm(false)} />}</>}</section></>}
  </aside>
}
