import { afterEach, describe, expect, it, vi } from 'vitest'
import { HttpError, NetworkError } from '../../../../../shared/http'
import { authenticatedApiClient } from '../../../api/apiClient'
import { buildAdminServicesPath, createAdminService, getAdminService, getAdminServices, updateAdminService, updateAdminServiceStatus } from './services-admin-api'
const id = '1ad575e6-0225-45ce-bb18-296407bc558b'
const service = { id, name: 'Elétrica', slug: 'eletrica', description: 'Reparos elétricos.', category: 'ELECTRICAL', isActive: true, createdAt: '2026-08-05T10:00:00.000Z', updatedAt: '2026-08-05T10:00:00.000Z' }
afterEach(() => vi.restoreAllMocks())
describe('services admin API', () => {
  it('monta paginação e somente filtros suportados preenchidos', () => expect(buildAdminServicesPath({ page: 2, limit: 20, search: '  elétrica ', category: ' ELECTRICAL ', isActive: false, orderBy: 'createdAt', sortOrder: 'desc' })).toBe('/services?page=2&limit=20&search=el%C3%A9trica&category=ELECTRICAL&isActive=false&orderBy=createdAt&sortOrder=desc'))
  it('lista com AbortSignal e valida paginação', async () => { const controller = new AbortController(); const response = { data: [service], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } }; const get = vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue(response); await expect(getAdminServices({ page: 1, limit: 20 }, controller.signal)).resolves.toEqual(response); expect(get).toHaveBeenCalledWith('/services?page=1&limit=20', { signal: controller.signal }) })
  it('usa detalhe por slug e mutações por id com payloads exatos', async () => { const get = vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue(service); const post = vi.spyOn(authenticatedApiClient, 'post').mockResolvedValue(service); const patch = vi.spyOn(authenticatedApiClient, 'patch').mockResolvedValue(service); await getAdminService('elétrica/segura'); await createAdminService({ name: '  Elétrica  ', slug: 'eletrica', description: ' Reparos elétricos. ', category: ' ELECTRICAL ' }); await updateAdminService(id, { name: '  Elétrica residencial ' }); await updateAdminServiceStatus(id, { isActive: false }); expect(get).toHaveBeenCalledWith('/services/el%C3%A9trica%2Fsegura', { signal: undefined }); expect(post).toHaveBeenCalledWith('/services', { name: 'Elétrica', slug: 'eletrica', description: 'Reparos elétricos.', category: 'ELECTRICAL' }, { signal: undefined }); expect(patch).toHaveBeenNthCalledWith(1, `/services/${id}`, { name: 'Elétrica residencial' }, { signal: undefined }); expect(patch).toHaveBeenNthCalledWith(2, `/services/${id}`, { isActive: false }, { signal: undefined }) })
  it('rejeita respostas com campos extras e slugs inválidos', async () => { vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue({ ...service, html: '<b>não</b>' }); await expect(getAdminService(service.slug)).rejects.toMatchObject({ name: 'ZodError' }); await expect(createAdminService({ ...service, slug: 'Slug Inválido' })).rejects.toMatchObject({ name: 'ZodError' }) })
  it.each([400, 401, 403, 404, 409])('preserva erro HTTP %s', async (status) => { const error = new HttpError({ status, statusText: 'Error', responseBody: {}, url: 'https://api.example.com/services', method: 'GET' }); vi.spyOn(authenticatedApiClient, 'get').mockRejectedValue(error); await expect(getAdminServices({ page: 1, limit: 20 })).rejects.toBe(error) })
  it('preserva erro de rede', async () => { const error = new NetworkError(); vi.spyOn(authenticatedApiClient, 'get').mockRejectedValue(error); await expect(getAdminServices({ page: 1, limit: 20 })).rejects.toBe(error) })
})
