import { afterEach, describe, expect, it, vi } from 'vitest'
import { HttpError, NetworkError } from '../../../../../shared/http'
import { authenticatedApiClient } from '../../../api/apiClient'
import { buildAdminAppointmentsPath, createAdminAppointment, getAdminAppointment, getAdminAppointments, updateAdminAppointment, updateAdminAppointmentStatus } from './appointments-admin-api'

const id = '1ad575e6-0225-45ce-bb18-296407bc558b'
const appointment = { id, serviceRequestId: '2ad575e6-0225-45ce-bb18-296407bc558b', scheduledAt: '2099-08-10T14:00:00.000Z', durationMinutes: 60, status: 'SCHEDULED' as const, notes: null, startedAt: null, completedAt: null, cancelledAt: null, createdAt: '2026-08-05T10:00:00.000Z', updatedAt: '2026-08-05T10:00:00.000Z', serviceRequest: { id: '2ad575e6-0225-45ce-bb18-296407bc558b', customerId: '3ad575e6-0225-45ce-bb18-296407bc558b', serviceId: '4ad575e6-0225-45ce-bb18-296407bc558b', description: 'Reparo elétrico aprovado.', status: 'SCHEDULED' as const, preferredDate: null, address: 'Endereço', city: 'Brasília', customer: { id: '3ad575e6-0225-45ce-bb18-296407bc558b', name: 'Cliente', phone: '61999999999', email: null }, service: { id: '4ad575e6-0225-45ce-bb18-296407bc558b', name: 'Elétrica', slug: 'eletrica', category: 'ELECTRICAL' } } }
afterEach(() => vi.restoreAllMocks())
describe('appointments admin API', () => {
  it('monta paginação e somente filtros preenchidos', () => expect(buildAdminAppointmentsPath({ page: 2, limit: 20, status: 'CONFIRMED', scheduledFrom: '2026-08-01T03:00:00.000Z' })).toBe('/appointments?page=2&limit=20&status=CONFIRMED&scheduledFrom=2026-08-01T03%3A00%3A00.000Z'))
  it('lista com signal e valida resposta', async () => { const controller = new AbortController(); const response = { data: [appointment], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } }; const get = vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue(response); await expect(getAdminAppointments({ page: 1, limit: 20 }, controller.signal)).resolves.toEqual(response); expect(get).toHaveBeenCalledWith('/appointments?page=1&limit=20', { signal: controller.signal }) })
  it('usa endpoints reais de detalhe, criação, edição e cancelamento sem DELETE', async () => { const get = vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue(appointment); const post = vi.spyOn(authenticatedApiClient, 'post').mockResolvedValue(appointment); const patch = vi.spyOn(authenticatedApiClient, 'patch').mockResolvedValue(appointment); const remove = vi.spyOn(authenticatedApiClient, 'delete'); await getAdminAppointment(id); await createAdminAppointment({ serviceRequestId: appointment.serviceRequestId, scheduledAt: appointment.scheduledAt, durationMinutes: 60 }); await updateAdminAppointment(id, { notes: null }); await updateAdminAppointmentStatus(id, { status: 'CANCELLED' }); expect(get).toHaveBeenCalledWith(`/appointments/${id}`, { signal: undefined }); expect(post).toHaveBeenCalledWith('/appointments', { serviceRequestId: appointment.serviceRequestId, scheduledAt: appointment.scheduledAt, durationMinutes: 60 }, { signal: undefined }); expect(patch).toHaveBeenNthCalledWith(1, `/appointments/${id}`, { notes: null }, { signal: undefined }); expect(patch).toHaveBeenNthCalledWith(2, `/appointments/${id}/status`, { status: 'CANCELLED' }, { signal: undefined }); expect(remove).not.toHaveBeenCalled() })
  it('rejeita resposta fora do contrato', async () => { vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue({ ...appointment, status: 'NO_SHOW' }); await expect(getAdminAppointment(id)).rejects.toMatchObject({ name: 'ZodError' }) })
  it.each([401, 403, 404])('preserva erro HTTP %s', async (status) => { const error = new HttpError({ status, statusText: 'Error', responseBody: {}, url: 'https://api.example.com/appointments', method: 'GET' }); vi.spyOn(authenticatedApiClient, 'get').mockRejectedValue(error); await expect(getAdminAppointments({ page: 1, limit: 20 })).rejects.toBe(error) })
  it('preserva erro de rede', async () => { const error = new NetworkError(); vi.spyOn(authenticatedApiClient, 'get').mockRejectedValue(error); await expect(getAdminAppointments({ page: 1, limit: 20 })).rejects.toBe(error) })
})
