import { afterEach, describe, expect, it, vi } from 'vitest'
import { HttpError, NetworkError } from '../../../../../shared/http'
import { authenticatedApiClient } from '../../../api/apiClient'
import { buildAdminUsersPath, createAdminUser, getAdminUser, getAdminUsers, updateAdminUser, updateAdminUserPassword, updateAdminUserStatus } from './users-admin-api'
const id = '1ad575e6-0225-45ce-bb18-296407bc558b'
const user = { id, name: 'Admin', email: 'admin@example.com', role: 'ADMIN', isActive: true, createdAt: '2026-08-05T10:00:00.000Z', updatedAt: '2026-08-05T10:00:00.000Z' }
afterEach(() => vi.restoreAllMocks())
describe('users admin API', () => {
  it('monta somente query params reais e preenchidos', () => expect(buildAdminUsersPath({ page: 2, limit: 20, search: ' Maria ', role: 'OPERATOR', isActive: false, orderBy: 'createdAt', sortOrder: 'desc' })).toBe('/users?page=2&limit=20&search=Maria&role=OPERATOR&isActive=false&orderBy=createdAt&sortOrder=desc'))
  it('lista com paginação e AbortSignal', async () => { const signal = new AbortController().signal; const response = { data: [user], pagination: { page: 1, limit: 20, total: 1, totalPages: 1 } }; const get = vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue(response); await expect(getAdminUsers({ page: 1, limit: 20 }, signal)).resolves.toEqual(response); expect(get).toHaveBeenCalledWith('/users?page=1&limit=20', { signal }) })
  it('usa endpoints, métodos e payloads exatos', async () => { const get = vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue(user); const post = vi.spyOn(authenticatedApiClient, 'post').mockResolvedValue(user); const patch = vi.spyOn(authenticatedApiClient, 'patch').mockResolvedValueOnce(user).mockResolvedValueOnce(user).mockResolvedValueOnce(undefined); await getAdminUser(id); await createAdminUser({ name: ' Admin ', email: ' ADMIN@example.com ', password: '12345678', role: 'ADMIN' }); await updateAdminUser(id, { role: 'OPERATOR' }); await updateAdminUserStatus(id, { isActive: false }); await expect(updateAdminUserPassword(id, { password: 'abcdefgh' })).resolves.toBeUndefined(); expect(get).toHaveBeenCalledWith(`/users/${id}`, { signal: undefined }); expect(post).toHaveBeenCalledWith('/users', { name: 'Admin', email: 'admin@example.com', password: '12345678', role: 'ADMIN' }, { signal: undefined }); expect(patch).toHaveBeenNthCalledWith(1, `/users/${id}`, { role: 'OPERATOR' }, { signal: undefined }); expect(patch).toHaveBeenNthCalledWith(2, `/users/${id}/status`, { isActive: false }, { signal: undefined }); expect(patch).toHaveBeenNthCalledWith(3, `/users/${id}/password`, { password: 'abcdefgh' }, { signal: undefined }) })
  it('rejeita resposta pública com campo extra', async () => { vi.spyOn(authenticatedApiClient, 'get').mockResolvedValue({ ...user, passwordHash: 'nope' }); await expect(getAdminUser(id)).rejects.toMatchObject({ name: 'ZodError' }) })
  it.each([400, 401, 403, 404, 409])('preserva erro HTTP %s', async (status) => { const error = new HttpError({ status, statusText: 'Error', responseBody: {}, url: 'https://api.example.com/users', method: 'GET' }); vi.spyOn(authenticatedApiClient, 'get').mockRejectedValue(error); await expect(getAdminUsers({ page: 1, limit: 20 })).rejects.toBe(error) })
  it('preserva erro de rede', async () => { const error = new NetworkError(); vi.spyOn(authenticatedApiClient, 'get').mockRejectedValue(error); await expect(getAdminUsers({ page: 1, limit: 20 })).rejects.toBe(error) })
})
