import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'
import { createServiceRequestComment, listServiceRequestTimeline } from '../api/service-request-timeline-api'
import { parseTimelineEvent, timelineEventTypes, type TimelineEventType } from '../types/contracts'
import { ServiceRequestTimeline } from './ServiceRequestTimeline'
import { TimelineCommentForm } from './TimelineCommentForm'
import { TimelineEvent } from './TimelineEvent'

vi.mock('../api/service-request-timeline-api', () => ({ listServiceRequestTimeline: vi.fn(), createServiceRequestComment: vi.fn() }))
const requestId = '1ad575e6-0225-45ce-bb18-296407bc558b'
const ids = { appointmentId: '3ad575e6-0225-45ce-bb18-296407bc558b', quoteId: '4ad575e6-0225-45ce-bb18-296407bc558b', paymentId: '5ad575e6-0225-45ce-bb18-296407bc558b' }
const metadata: Record<TimelineEventType, unknown> = {
  REQUEST_CREATED: null, COMMENT_ADDED: null, STATUS_CHANGED: { from: 'PENDING', to: 'CONTACTED' },
  APPOINTMENT_CREATED: { appointmentId: ids.appointmentId, scheduledAt: '2026-08-06T17:00:00.000Z' },
  APPOINTMENT_RESCHEDULED: { appointmentId: ids.appointmentId, scheduledAtFrom: '2026-08-06T17:00:00.000Z', scheduledAtTo: '2026-08-07T12:00:00.000Z' },
  APPOINTMENT_STATUS_CHANGED: { appointmentId: ids.appointmentId, from: 'SCHEDULED', to: 'CONFIRMED' },
  QUOTE_CREATED: { quoteId: ids.quoteId }, QUOTE_STATUS_CHANGED: { quoteId: ids.quoteId, from: 'DRAFT', to: 'SENT' },
  PAYMENT_CREATED: { paymentId: ids.paymentId, quoteId: ids.quoteId }, PAYMENT_STATUS_CHANGED: { paymentId: ids.paymentId, quoteId: ids.quoteId, from: 'PENDING', to: 'PAID' },
}
function event(type: TimelineEventType, actor: 'ADMIN' | 'OPERATOR' | null = 'ADMIN', id = '2ad575e6-0225-45ce-bb18-296407bc558b') { return parseTimelineEvent({ id, serviceRequestId: requestId, type, title: 'Título do backend', description: 'Descrição segura', metadata: metadata[type], createdAt: '2026-08-05T12:00:00.000Z', actor: actor ? { id: '6ad575e6-0225-45ce-bb18-296407bc558b', name: 'Ana', email: 'ana@example.com', role: actor } : null }) }
function wrapper(children: React.ReactNode) { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter>{children}</MemoryRouter></QueryClientProvider>) }

describe('componentes da timeline', () => {
  it.each(timelineEventTypes)('renderiza %s com estrutura acessível e metadata semântico', (type) => { wrapper(<ol><TimelineEvent event={event(type)} /></ol>); expect(screen.getByRole('listitem')).toHaveAccessibleName(); expect(screen.getByText(/Por Ana/)).toHaveTextContent('Administrador'); expect(screen.queryByText(/\{"/)).not.toBeInTheDocument() })
  it('renderiza operador e ator nulo', () => { const { rerender } = wrapper(<ol><TimelineEvent event={event('COMMENT_ADDED', 'OPERATOR')} /></ol>); expect(screen.getByText(/Por Ana/)).toHaveTextContent('Operador'); rerender(<QueryClientProvider client={new QueryClient()}><MemoryRouter><ol><TimelineEvent event={event('COMMENT_ADDED', null)} /></ol></MemoryRouter></QueryClientProvider>); expect(screen.getByText('Autor não identificado')).toBeInTheDocument() })
  it('informa metadata inválido sem expor conteúdo', () => { const warn = vi.spyOn(console, 'warn').mockImplementation(() => undefined); try { const { metadataValid, ...raw } = event('STATUS_CHANGED'); expect(metadataValid).toBe(true); const invalid = parseTimelineEvent({ ...raw, metadata: { secret: 'não mostrar' } }); wrapper(<ol><TimelineEvent event={invalid} /></ol>); expect(screen.getByText('Detalhes adicionais indisponíveis.')).toBeInTheDocument(); expect(screen.queryByText('não mostrar')).not.toBeInTheDocument(); if (import.meta.env.DEV) expect(warn).toHaveBeenCalledWith('Timeline metadata inválido', { eventId: raw.id, type: raw.type }); else expect(warn).not.toHaveBeenCalled() } finally { warn.mockRestore() } })
  it('filtra, ordena, carrega mais e mostra o fim', async () => { vi.mocked(listServiceRequestTimeline).mockResolvedValueOnce({ data: [event('REQUEST_CREATED')], pagination: { page: 1, limit: 10, total: 2, totalPages: 2 } }).mockResolvedValueOnce({ data: [event('COMMENT_ADDED', 'ADMIN', '7ad575e6-0225-45ce-bb18-296407bc558b')], pagination: { page: 2, limit: 10, total: 2, totalPages: 2 } }).mockResolvedValue({ data: [], pagination: { page: 1, limit: 10, total: 0, totalPages: 0 } }); wrapper(<ServiceRequestTimeline serviceRequestId={requestId} />); expect(await screen.findByText('1 de 2 eventos carregados')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Carregar mais eventos' })); expect(await screen.findByText('2 de 2 eventos carregados')).toBeInTheDocument(); expect(screen.getByText('Fim do histórico.')).toBeInTheDocument(); await userEvent.selectOptions(screen.getByLabelText('Tipo de evento'), 'COMMENT_ADDED'); await waitFor(() => expect(vi.mocked(listServiceRequestTimeline).mock.calls.at(-1)?.[1]).toMatchObject({ type: 'COMMENT_ADDED' })); await userEvent.selectOptions(screen.getByLabelText('Ordem'), 'asc'); await waitFor(() => expect(vi.mocked(listServiceRequestTimeline).mock.calls.at(-1)?.[1]).toMatchObject({ sortOrder: 'asc' })) })
  it('mostra vazio, erro e retry', async () => { vi.mocked(listServiceRequestTimeline).mockResolvedValueOnce({ data: [], pagination: { page: 1, limit: 10, total: 0, totalPages: 0 } }); const view = wrapper(<ServiceRequestTimeline serviceRequestId={requestId} />); expect(await screen.findByText('Nenhum evento encontrado para este filtro.')).toBeInTheDocument(); view.unmount(); vi.mocked(listServiceRequestTimeline).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({ data: [], pagination: { page: 1, limit: 10, total: 0, totalPages: 0 } }); wrapper(<ServiceRequestTimeline serviceRequestId={requestId} />); expect(await screen.findByRole('alert')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Tentar novamente' })); expect(await screen.findByText('Nenhum evento encontrado para este filtro.')).toBeInTheDocument() })
  it('faz trim, bloqueia vazio/duplo envio, limpa no sucesso e preserva no erro', async () => { let resolve: ((value: ReturnType<typeof event>) => void) | undefined; vi.mocked(createServiceRequestComment).mockReturnValueOnce(new Promise((done) => { resolve = done })).mockRejectedValueOnce(new Error('offline')); wrapper(<TimelineCommentForm serviceRequestId={requestId} />); const textarea = screen.getByLabelText('Comentário'); const submit = screen.getByRole('button', { name: 'Adicionar comentário' }); expect(submit).toBeDisabled(); await userEvent.type(textarea, '  Nota interna  '); await userEvent.click(submit); expect(submit).toBeDisabled(); fireEvent.click(submit); expect(createServiceRequestComment).toHaveBeenCalledOnce(); resolve?.(event('COMMENT_ADDED')); expect(await screen.findByText('Comentário interno adicionado.')).toBeInTheDocument(); expect(textarea).toHaveValue(''); await userEvent.type(textarea, 'Manter em caso de erro'); await userEvent.click(submit); expect(await screen.findByText('Ocorreu um erro inesperado. Tente novamente.')).toBeInTheDocument(); expect(textarea).toHaveValue('Manter em caso de erro'); expect(createServiceRequestComment).toHaveBeenLastCalledWith(requestId, { content: 'Manter em caso de erro' }) })
})
