import { beforeEach, describe, expect, it, vi } from 'vitest'
import { authenticatedApiClient } from '../../../api/apiClient'
import { buildQuotesPath, createQuote, getPayments, getQuote, updatePaymentStatus, updateQuote } from './finance-admin-api'

vi.mock('../../../api/apiClient', () => ({ authenticatedApiClient: { get: vi.fn(), post: vi.fn(), patch: vi.fn() } }))
const id = '11111111-1111-4111-8111-111111111111'
const quote = { id, serviceRequestId: id, subtotalCents: 10000, discountCents: 0, totalCents: 10000, description: null, notes: null, status: 'DRAFT', validUntil: null, approvedAt: null, rejectedAt: null, cancelledAt: null, createdAt: '2026-08-05T12:00:00.000Z', updatedAt: '2026-08-05T12:00:00.000Z', serviceRequest: { id, status: 'QUOTED', description: 'Teste', customer: { id, name: 'Ana', phone: '61999999999', email: null }, service: { id, name: 'Elétrica', slug: 'eletrica', category: 'Casa' } }, paidTotalCents: 0, remainingCents: 10000, paymentStatus: 'UNPAID' }
describe('finance API', () => {
  beforeEach(() => vi.clearAllMocks())
  it('serializes only real quote filters', () => expect(buildQuotesPath({ page: 2, limit: 20, status: 'DRAFT', orderBy: 'createdAt', sortOrder: 'desc' })).toBe('/quotes?page=2&limit=20&status=DRAFT&orderBy=createdAt&sortOrder=desc'))
  it('sends exact creation payload without totalCents', async () => { vi.mocked(authenticatedApiClient.post).mockResolvedValue(quote); await createQuote({ serviceRequestId: id, subtotalCents: 10000 }); expect(authenticatedApiClient.post).toHaveBeenCalledWith('/quotes', { serviceRequestId: id, subtotalCents: 10000 }, { signal: undefined }); expect(authenticatedApiClient.post).not.toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ totalCents: expect.anything() }), expect.anything()) })
  it('sends exact update payload without serviceRequestId, totalCents or status', async () => { vi.mocked(authenticatedApiClient.patch).mockResolvedValue(quote); await updateQuote(id, { notes: 'Nova' }); expect(authenticatedApiClient.patch).toHaveBeenCalledWith(`/quotes/${id}`, { notes: 'Nova' }, { signal: undefined }); await expect(updateQuote(id, { notes: 'x', status: 'SENT' } as never)).rejects.toThrow(); await expect(updateQuote(id, { totalCents: 1 } as never)).rejects.toThrow(); await expect(updateQuote(id, { serviceRequestId: id } as never)).rejects.toThrow() })
  it('aceita pagamentos somente como array e rejeita respostas inventadas ou inválidas', async () => { vi.mocked(authenticatedApiClient.get).mockResolvedValue([]); await expect(getPayments(id)).resolves.toEqual([]); vi.mocked(authenticatedApiClient.get).mockResolvedValue({ data: [], pagination: { page: 1, limit: 20, total: 0, totalPages: 0 } }); await expect(getPayments(id)).rejects.toThrow(); vi.mocked(authenticatedApiClient.get).mockResolvedValue([{ unexpected: true }]); await expect(getPayments(id)).rejects.toThrow() })
  it.each([401, 403, 404, 409])('propaga erro HTTP %s sem inventar resposta', async (status) => { const error = Object.assign(new Error(`HTTP ${status}`), { status }); vi.mocked(authenticatedApiClient.get).mockRejectedValue(error); await expect(getQuote(id)).rejects.toBe(error) })
  it('propaga erro de rede sem inventar resposta', async () => { const error = new Error('network'); vi.mocked(authenticatedApiClient.get).mockRejectedValue(error); await expect(getQuote(id)).rejects.toBe(error) })
  it('preserves AbortSignal and validates strict responses', async () => { const signal = new AbortController().signal; vi.mocked(authenticatedApiClient.get).mockResolvedValue([]); await getPayments(id, signal); expect(authenticatedApiClient.get).toHaveBeenCalledWith(`/quotes/${id}/payments`, { signal }); vi.mocked(authenticatedApiClient.patch).mockResolvedValue({ unexpected: true }); await expect(updatePaymentStatus(id, { status: 'PAID' })).rejects.toThrow() })
})
