import { useEffect, useRef, useState } from 'react'
import { useAuth } from '../../../auth/useAuth'
import { useUser } from '../api/useUser'
import { useUpdateUser } from '../api/useUpdateUser'
import { useUpdateUserPassword } from '../api/useUpdateUserPassword'
import { useUpdateUserStatus } from '../api/useUpdateUserStatus'
import { toUserUiError } from '../user-errors'
import { PasswordDialog } from './PasswordDialog'
import { RoleBadge } from './RoleBadge'
import { StatusBadge } from './StatusBadge'
import { UserForm } from './UserForm'
import { updateUserSchema } from '../types/contracts'
const dateTime = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeStyle: 'short' })
export function UserDetails({ id, onClose }: { id: string; onClose: () => void }) {
  const auth = useAuth(); const query = useUser(id); const update = useUpdateUser(id); const status = useUpdateUserStatus(id); const password = useUpdateUserPassword(id); const closeRef = useRef<HTMLButtonElement>(null); const [success, setSuccess] = useState(''); const [showPassword, setShowPassword] = useState(false)
  useEffect(() => { closeRef.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape) }, [onClose])
  const user = query.data
  async function changeStatus() { if (!user || status.isPending || user.id === auth.user?.id) return; const next = !user.isActive; if (!window.confirm(`${next ? 'Reativar' : 'Desativar'} este usuário?`)) return; setSuccess(''); try { await status.mutateAsync({ isActive: next }); setSuccess(`Usuário ${next ? 'reativado' : 'desativado'} com sucesso.`) } catch { /* mensagem segura abaixo */ } }
  return <aside className="amigo-admin-drawer" role="dialog" aria-modal="true" aria-labelledby="user-title"><div className="amigo-admin-drawer-header"><h2 id="user-title">Detalhes do usuário</h2><button ref={closeRef} type="button" onClick={onClose}>Fechar</button></div>{query.isPending && <p role="status">Carregando detalhes…</p>}{query.isError && <div role="alert" className="amigo-admin-state"><p>{toUserUiError(query.error)}</p><button type="button" onClick={() => void query.refetch()}>Tentar novamente</button></div>}{user && <><dl className="amigo-admin-details-list"><div><dt>Nome</dt><dd>{user.name}</dd></div><div><dt>E-mail</dt><dd>{user.email}</dd></div><div><dt>Papel</dt><dd><RoleBadge role={user.role} /></dd></div><div><dt>Status</dt><dd><StatusBadge isActive={user.isActive} /></dd></div><div><dt>Criado em</dt><dd>{dateTime.format(new Date(user.createdAt))}</dd></div><div><dt>Atualizado em</dt><dd>{dateTime.format(new Date(user.updatedAt))}</dd></div></dl><section><h3>Editar dados</h3><UserForm user={user} isPending={update.isPending} error={update.error} onSubmit={async (input) => { setSuccess(''); try { const updated = await update.mutateAsync(updateUserSchema.parse(input)); if (updated.id === auth.user?.id && updated.role !== auth.user.role) { auth.logout(); return } setSuccess('Usuário atualizado com sucesso.') } catch { /* mensagem segura no formulário */ } }} /></section><section className="amigo-admin-status-update"><h3>{user.isActive ? 'Desativar usuário' : 'Reativar usuário'}</h3>{user.id === auth.user?.id ? <p>Você não pode desativar a própria conta.</p> : <button type="button" disabled={status.isPending} onClick={() => void changeStatus()}>{status.isPending ? 'Atualizando…' : user.isActive ? 'Desativar usuário' : 'Reativar usuário'}</button>}{status.isError && <p role="alert" className="amigo-form-message amigo-form-message-error">{toUserUiError(status.error)}</p>}</section>{showPassword ? <PasswordDialog isPending={password.isPending} error={undefined} onClose={() => { password.reset(); setShowPassword(false) }} onSubmit={async (nextPassword) => { try { await password.mutateAsync({ password: nextPassword }) } finally { password.reset() } }} /> : <button type="button" onClick={() => { password.reset(); setShowPassword(true) }}>Alterar senha</button>}{success && <p role="status" className="amigo-form-message amigo-form-message-success">{success}</p>}</>}</aside>
}
