import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { PasswordDialog } from './PasswordDialog'
import { UserFilters } from './UserFilters'
import { UserForm } from './UserForm'
import { UsersTable } from './UsersTable'
const user = { id: '1ad575e6-0225-45ce-bb18-296407bc558b', name: 'Admin', email: 'admin@example.com', role: 'ADMIN' as const, isActive: false, createdAt: '2026-08-05T10:00:00.000Z', updatedAt: '2026-08-05T10:00:00.000Z' }
describe('user admin components', () => {
  it('renderiza tabela, badges e detalhes', () => { const details = vi.fn(); render(<UsersTable users={[user]} onDetails={details} />); expect(screen.getByText('Administrador')).toBeInTheDocument(); expect(screen.getByText('Inativo')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Ver detalhes de Admin' })); expect(details).toHaveBeenCalledWith(user.id) })
  it('aplica e limpa filtros reais', () => { const apply = vi.fn(); const clear = vi.fn(); render(<UserFilters values={{ orderBy: 'name', sortOrder: 'asc' }} onApply={apply} onClear={clear} />); fireEvent.change(screen.getByLabelText('Buscar'), { target: { value: ' Maria ' } }); fireEvent.change(screen.getByLabelText('Papel'), { target: { value: 'OPERATOR' } }); fireEvent.click(screen.getByRole('button', { name: 'Aplicar filtros' })); expect(apply).toHaveBeenCalledWith({ search: 'Maria', role: 'OPERATOR', isActive: undefined, orderBy: 'name', sortOrder: 'asc' }); fireEvent.click(screen.getByRole('button', { name: 'Limpar' })); expect(clear).toHaveBeenCalledOnce() })
  it('valida criação e bloqueia envio pendente', () => { const submit = vi.fn(); const { rerender } = render(<UserForm isPending={false} onSubmit={submit} />); fireEvent.change(screen.getByLabelText('Nome'), { target: { value: 'Maria' } }); fireEvent.change(screen.getByLabelText('E-mail'), { target: { value: 'maria@example.com' } }); fireEvent.change(screen.getByLabelText('Senha'), { target: { value: 'curta' } }); fireEvent.click(screen.getByRole('button', { name: 'Criar usuário' })); expect(screen.getByRole('alert')).toHaveTextContent('8 e 128'); expect(submit).not.toHaveBeenCalled(); rerender(<UserForm isPending onSubmit={submit} />); expect(screen.getByRole('button', { name: 'Salvando…' })).toBeDisabled() })
  it('limpa senha após erro e impede envio duplicado', async () => { const submit = vi.fn().mockRejectedValue(new Error('falhou')); render(<PasswordDialog isPending={false} onSubmit={submit} onClose={vi.fn()} />); const password = screen.getByLabelText('Nova senha'); fireEvent.change(password, { target: { value: 'abcdefgh' } }); fireEvent.change(screen.getByLabelText('Confirmar nova senha'), { target: { value: 'abcdefgh' } }); fireEvent.click(screen.getByRole('button', { name: 'Alterar senha' })); await waitFor(() => expect(submit).toHaveBeenCalledOnce()); expect(password).toHaveValue('') })
})
