import { useState, type FormEvent } from 'react'
import { toUserUiError } from '../user-errors'
import { createUserSchema, updateUserSchema, type AdminUser, type CreateUserInput, type UpdateUserInput, type UserRole } from '../types/contracts'

type Props = { user?: AdminUser; isPending: boolean; error?: unknown; onSubmit: (input: CreateUserInput | UpdateUserInput) => Promise<void>; onSuccess?: () => void }
export function UserForm({ user, isPending, error, onSubmit, onSuccess }: Props) {
  const [message, setMessage] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (isPending) return; const formElement = event.currentTarget; const form = new FormData(formElement); const base = { name: form.get('name'), email: form.get('email'), role: form.get('role') as UserRole }; const parsed = user ? updateUserSchema.safeParse(base) : createUserSchema.safeParse({ ...base, password: form.get('password'), isActive: form.get('isActive') === 'on' }); if (!parsed.success) { const field = parsed.error.issues[0]?.path[0]; setMessage(field === 'email' ? 'Informe um e-mail válido.' : field === 'password' ? 'A senha deve ter entre 8 e 128 caracteres.' : 'Revise os dados informados.'); return } setMessage(''); try { await onSubmit(parsed.data); if (!user) formElement.reset(); onSuccess?.() } finally { const password = formElement.elements.namedItem('password'); if (password instanceof HTMLInputElement) password.value = '' } }
  return <form onSubmit={(event) => void submit(event)} aria-label={user ? 'Editar usuário' : 'Criar usuário'}><label>Nome<input name="name" defaultValue={user?.name ?? ''} minLength={2} maxLength={120} required disabled={isPending} /></label><label>E-mail<input name="email" type="email" defaultValue={user?.email ?? ''} maxLength={320} required disabled={isPending} /></label>{!user && <label>Senha<input name="password" type="password" minLength={8} maxLength={128} required disabled={isPending} autoComplete="new-password" /></label>}<label>Papel<select name="role" defaultValue={user?.role ?? 'OPERATOR'} disabled={isPending}><option value="OPERATOR">Operador</option><option value="ADMIN">Administrador</option></select></label>{!user && <label><input name="isActive" type="checkbox" defaultChecked disabled={isPending} /> Usuário ativo</label>}<button className="amigo-button" type="submit" disabled={isPending}>{isPending ? 'Salvando…' : user ? 'Salvar alterações' : 'Criar usuário'}</button>{message && <p role="alert" className="amigo-form-message amigo-form-message-error">{message}</p>}{error !== undefined && <p role="alert" className="amigo-form-message amigo-form-message-error">{toUserUiError(error)}</p>}</form>
}
