import { useState, type FormEvent } from 'react'
import { HttpError } from '../../../../../shared/http'
import { toUiError } from '../../../api/errors'
import { SERVICE_CATEGORIES, createServiceSchema, type AdminService, type CreateServiceInput } from '../types/contracts'

function errorMessage(error: unknown) { return error instanceof HttpError && error.status === 409 ? 'Já existe um serviço com este slug.' : toUiError(error).userMessage }
export function ServiceForm({ service, isPending, error, onSubmit }: { service?: AdminService; isPending: boolean; error?: unknown; onSubmit: (input: CreateServiceInput) => Promise<void> }) {
  const [message, setMessage] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (isPending) return; const form = new FormData(event.currentTarget); const parsed = createServiceSchema.safeParse({ name: form.get('name'), slug: form.get('slug'), description: form.get('description'), category: form.get('category') }); if (!parsed.success) { const field = parsed.error.issues[0]?.path[0]; setMessage(field === 'slug' ? 'Use somente letras minúsculas, números e hífens, sem hífen no início ou fim.' : field === 'category' ? 'Informe uma categoria com até 100 caracteres.' : field === 'description' ? 'Informe uma descrição com até 1.000 caracteres.' : 'Informe um nome entre 3 e 120 caracteres.'); return } setMessage(''); await onSubmit(parsed.data) }
  return <form onSubmit={(event) => void submit(event)} aria-label={service ? 'Editar serviço' : 'Criar serviço'}><label>Nome<input name="name" defaultValue={service?.name ?? ''} minLength={3} maxLength={120} required disabled={isPending} /></label><label>Slug<input name="slug" defaultValue={service?.slug ?? ''} pattern="[a-z0-9]+(-[a-z0-9]+)*" required disabled={isPending} aria-describedby="slug-help" /></label><p id="slug-help">O slug não é gerado automaticamente. Confirme-o antes de salvar; alterá-lo não publica nem renomeia uma página SEO.</p><label>Descrição<textarea name="description" defaultValue={service?.description ?? ''} minLength={1} maxLength={1000} required disabled={isPending} /></label><label htmlFor="service-category">Categoria</label><input id="service-category" name="category" defaultValue={service?.category ?? ''} list="service-form-categories" maxLength={100} required disabled={isPending} /><datalist id="service-form-categories">{Object.entries(SERVICE_CATEGORIES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</datalist><button className="amigo-button" type="submit" disabled={isPending}>{isPending ? 'Salvando…' : service ? 'Salvar alterações' : 'Criar serviço'}</button>{message && <p role="alert" className="amigo-form-message amigo-form-message-error">{message}</p>}{error !== undefined && <p role="alert" className="amigo-form-message amigo-form-message-error">{errorMessage(error)}</p>}</form>
}
