import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../../auth/useAuth'
import { toUiError } from '../../../api/errors'
import { useAdminService } from '../api/useAdminService'
import { useUpdateService } from '../api/useUpdateService'
import { useUpdateServiceStatus } from '../api/useUpdateServiceStatus'
import { getServiceCategoryLabel, type CreateServiceInput } from '../types/contracts'
import { ServiceForm } from './ServiceForm'
import { getPublishedServicePath } from '../publication'
import { ServicePublicationBadge } from './ServicePublicationBadge'
import { ServiceStatusBadge } from './ServiceStatusBadge'
const dateTime = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeStyle: 'short' })
export function ServiceDetails({ slug, onClose, onSlugChange }: { slug: string; onClose: () => void; onSlugChange: (slug: string) => void }) {
  const auth = useAuth(); const query = useAdminService(slug); const service = query.data; const update = useUpdateService(service?.id ?? '', slug); const status = useUpdateServiceStatus(service?.id ?? '', slug); const closeRef = useRef<HTMLButtonElement>(null); const [success, setSuccess] = useState('')
  useEffect(() => { closeRef.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape) }, [onClose])
  async function changeStatus() { if (!service || status.isPending) return; const next = !service.isActive; if (!window.confirm(`${next ? 'Ativar' : 'Desativar'} este serviço operacional? A página pública editorial, se existir, não será alterada.`)) return; setSuccess(''); try { await status.mutateAsync({ isActive: next }); setSuccess(`Serviço ${next ? 'ativado' : 'desativado'} com sucesso. A publicação editorial não foi alterada.`) } catch { /* erro seguro abaixo */ } }
  async function submit(input: CreateServiceInput) { if (!service) return; setSuccess(''); const updated = await update.mutateAsync(input); setSuccess('Serviço atualizado com sucesso. A publicação editorial não foi alterada.'); if (updated.slug !== slug) onSlugChange(updated.slug) }
  const publicPath = service ? getPublishedServicePath(service.slug) : undefined
  return <aside className="amigo-admin-drawer" role="dialog" aria-modal="true" aria-labelledby="service-title"><div className="amigo-admin-drawer-header"><h2 id="service-title">Detalhes do serviço</h2><button ref={closeRef} type="button" onClick={onClose}>Fechar</button></div>{query.isPending && <p role="status">Carregando detalhes…</p>}{query.isError && <div role="alert" className="amigo-admin-state"><p>{toUiError(query.error).userMessage}</p><button type="button" onClick={() => void query.refetch()}>Tentar novamente</button></div>}{service && <><dl className="amigo-admin-details-list"><div><dt>Nome</dt><dd>{service.name}</dd></div><div><dt>Slug operacional</dt><dd>{service.slug}</dd></div><div><dt>Descrição</dt><dd>{service.description}</dd></div><div><dt>Categoria</dt><dd>{getServiceCategoryLabel(service.category)}</dd></div><div><dt>Status</dt><dd><ServiceStatusBadge isActive={service.isActive} /></dd></div><div><dt>Publicação editorial</dt><dd><ServicePublicationBadge slug={service.slug} /></dd></div><div><dt>Criado em</dt><dd>{dateTime.format(new Date(service.createdAt))}</dd></div><div><dt>Atualizado em</dt><dd>{dateTime.format(new Date(service.updatedAt))}</dd></div></dl>{publicPath ? <section><h3>Página pública publicada</h3><p><Link to={publicPath}>Abrir página pública</Link></p><p>O conteúdo SEO desta página é editorial e versionado no código.</p></section> : <section><h3>Sem página pública publicada</h3><p>Este cadastro pertence somente ao catálogo operacional. Nenhuma rota foi criada.</p></section>}{auth.user?.role === 'ADMIN' && <><section><h3>Editar dados operacionais</h3><ServiceForm service={service} isPending={update.isPending} error={update.error} onSubmit={submit} /></section><section className="amigo-admin-status-update"><h3>{service.isActive ? 'Desativar serviço' : 'Ativar serviço'}</h3><p>O status afeta o catálogo dinâmico, mas não cria, remove ou altera conteúdo editorial local.</p><button type="button" disabled={status.isPending} onClick={() => void changeStatus()}>{status.isPending ? 'Atualizando…' : service.isActive ? 'Desativar serviço' : 'Ativar serviço'}</button>{status.isError && <p role="alert" className="amigo-form-message amigo-form-message-error">{toUiError(status.error).userMessage}</p>}</section></>}{auth.user?.role !== 'ADMIN' && <p>Seu perfil possui acesso de leitura. Alterações exigem perfil ADMIN.</p>}{success && <p role="status" className="amigo-form-message amigo-form-message-success">{success}</p>}</> }</aside>
}
