import { fireEvent, render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { ServiceFilters } from './ServiceFilters'
import { ServiceForm } from './ServiceForm'
import { getPublishedServicePath } from '../publication'
import { ServicePublicationBadge } from './ServicePublicationBadge'
import { ServicesTable } from './ServicesTable'
const service = { id: '1ad575e6-0225-45ce-bb18-296407bc558b', name: 'Elétrica', slug: 'eletrica', description: 'Reparos.', category: 'ELECTRICAL', isActive: false, createdAt: '2026-08-05T10:00:00.000Z', updatedAt: '2026-08-05T10:00:00.000Z' }
describe('service admin components', () => {
  it('renderiza tabela, labels, status, publicação e detalhes', () => { const details = vi.fn(); render(<ServicesTable services={[service]} onDetails={details} />); expect(screen.getByText('Inativo')).toBeInTheDocument(); expect(screen.getByText('Página publicada')).toBeInTheDocument(); expect(screen.getAllByText('Elétrica')).toHaveLength(2); fireEvent.click(screen.getByRole('button', { name: 'Ver detalhes de Elétrica' })); expect(details).toHaveBeenCalledWith('eletrica') })
  it('não associa slug remoto desconhecido a página pública', () => { expect(getPublishedServicePath('servico-api-novo')).toBeUndefined(); expect(getPublishedServicePath('eletrica')).toBe('/servicos/eletrica'); render(<ServicePublicationBadge slug="servico-api-novo" />); expect(screen.getByText('Sem página pública')).toBeInTheDocument() })
  it('aplica filtros reais e limpa', () => { const apply = vi.fn(); const clear = vi.fn(); render(<ServiceFilters values={{ orderBy: 'name', sortOrder: 'asc' }} onApply={apply} onClear={clear} />); fireEvent.change(screen.getByLabelText('Buscar'), { target: { value: ' elétrica ' } }); fireEvent.change(screen.getByLabelText('Categoria'), { target: { value: 'ELECTRICAL' } }); fireEvent.change(screen.getByLabelText('Status'), { target: { value: 'false' } }); fireEvent.click(screen.getByRole('button', { name: 'Aplicar filtros' })); expect(apply).toHaveBeenCalledWith({ search: 'elétrica', category: 'ELECTRICAL', isActive: false, orderBy: 'name', sortOrder: 'asc' }); fireEvent.click(screen.getByRole('button', { name: 'Limpar' })); expect(clear).toHaveBeenCalledOnce() })
  it('valida slug e impede envio duplicado', () => { const submit = vi.fn(); const { rerender } = render(<ServiceForm isPending={false} onSubmit={submit} />); fireEvent.change(screen.getByLabelText('Nome'), { target: { value: 'Serviço novo' } }); fireEvent.change(screen.getByLabelText('Slug'), { target: { value: 'Slug Inválido' } }); fireEvent.change(screen.getByLabelText('Descrição'), { target: { value: 'Descrição' } }); fireEvent.change(screen.getByLabelText('Categoria'), { target: { value: 'CUSTOM' } }); fireEvent.submit(screen.getByRole('form', { name: 'Criar serviço' })); expect(screen.getByRole('alert')).toHaveTextContent('letras minúsculas'); expect(submit).not.toHaveBeenCalled(); rerender(<ServiceForm isPending onSubmit={submit} />); expect(screen.getByRole('button', { name: 'Salvando…' })).toBeDisabled() })
})
