import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { AdminPageMetadata } from '../../../components/AdminPageMetadata'
import { toUiError } from '../../../api/errors'
import { useQuotes } from '../api/finance-hooks'
import { QuoteCreateDialog } from '../components/QuoteCreateDialog'
import { QuoteDetails } from '../components/QuoteDetails'
import { QuoteStatusBadge } from '../components/FinanceBadges'
import { quoteLabels } from '../components/labels'
import { quoteStatuses, type QuoteFilters } from '../types/contracts'
import { centsToCurrency } from '../utils/money'

const PAGE_SIZE = 20
const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const date = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short' })
const isoBoundary = (value: string | null, end = false) => value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T${end ? '23:59:59.999' : '00:00:00.000'}`).toISOString() : undefined
const paymentSituation = { UNPAID: 'Não pago', PARTIALLY_PAID: 'Parcialmente pago', PAID: 'Pago' } as const

export function AdminFinancePage() {
  const [params, setParams] = useSearchParams(); const [success, setSuccess] = useState('')
  const pageValue = Number(params.get('page')); const page = Number.isInteger(pageValue) && pageValue > 0 ? pageValue : 1
  const status = quoteStatuses.find((value) => value === params.get('status')); const orderByValues = ['createdAt', 'updatedAt', 'validUntil', 'status', 'totalCents'] as const; const orderBy = orderByValues.find((value) => value === params.get('orderBy')) ?? 'createdAt'; const sortOrder = params.get('sortOrder') === 'asc' ? 'asc' : 'desc'
  const selected = uuid.test(params.get('quote') ?? '') ? params.get('quote') ?? undefined : undefined
  const createdFromInput = params.get('createdFrom'); const createdToInput = params.get('createdTo'); const validUntilFromInput = params.get('validUntilFrom'); const validUntilToInput = params.get('validUntilTo')
  const filters = useMemo<QuoteFilters>(() => ({ page, limit: PAGE_SIZE, status, createdFrom: isoBoundary(createdFromInput), createdTo: isoBoundary(createdToInput, true), validUntilFrom: isoBoundary(validUntilFromInput), validUntilTo: isoBoundary(validUntilToInput, true), orderBy, sortOrder }), [createdFromInput, createdToInput, orderBy, page, sortOrder, status, validUntilFromInput, validUntilToInput])
  const query = useQuotes(filters); const update = useCallback((values: Record<string, string | undefined>) => setParams((current) => { const next = new URLSearchParams(current); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); return next }, { replace: true, preventScrollReset: true }), [setParams])
  useEffect(() => { const totalPages = query.data?.pagination.totalPages; if (totalPages && page > totalPages) update({ page: String(totalPages) }) }, [page, query.data?.pagination.totalPages, update])
  function apply(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); update({ page: undefined, status: String(data.get('status') || '') || undefined, createdFrom: String(data.get('createdFrom') || '') || undefined, createdTo: String(data.get('createdTo') || '') || undefined, validUntilFrom: String(data.get('validUntilFrom') || '') || undefined, validUntilTo: String(data.get('validUntilTo') || '') || undefined, orderBy: String(data.get('orderBy')), sortOrder: String(data.get('sortOrder')) }) }
  return <main id="conteudo-principal" className="amigo-admin-page amigo-finance-page"><AdminPageMetadata title="Financeiro — Amigo do Lar" /><header className="amigo-admin-header"><div><p className="amigo-eyebrow">Portal administrativo</p><h1>Financeiro</h1><p>Orçamentos, saldos e pagamentos vinculados às solicitações.</p></div><div className="amigo-admin-header-actions"><button className="amigo-button" onClick={() => update({ create: '1', quote: undefined })}>Novo orçamento</button><Link className="amigo-button amigo-button-secondary" to="/admin">Dashboard</Link></div></header>
    <section className="amigo-admin-card" aria-label="Filtros e orçamentos"><form className="amigo-admin-filters" onSubmit={apply}><label>Status<select name="status" defaultValue={status ?? ''}><option value="">Todos</option>{quoteStatuses.map((value) => <option key={value} value={value}>{quoteLabels[value]}</option>)}</select></label><label>Criado de<input type="date" name="createdFrom" defaultValue={createdFromInput ?? ''} /></label><label>Criado até<input type="date" name="createdTo" defaultValue={createdToInput ?? ''} /></label><label>Validade de<input type="date" name="validUntilFrom" defaultValue={validUntilFromInput ?? ''} /></label><label>Validade até<input type="date" name="validUntilTo" defaultValue={validUntilToInput ?? ''} /></label><label>Ordenar por<select name="orderBy" defaultValue={orderBy}><option value="createdAt">Criação</option><option value="updatedAt">Atualização</option><option value="validUntil">Validade</option><option value="status">Status</option><option value="totalCents">Total</option></select></label><label>Direção<select name="sortOrder" defaultValue={sortOrder}><option value="desc">Decrescente</option><option value="asc">Crescente</option></select></label><div><button type="submit">Aplicar filtros</button><button type="button" onClick={() => setParams({}, { replace: true })}>Limpar</button></div></form>
      {query.isFetching && <p role="status">Atualizando orçamentos…</p>}{query.isError && <div className="amigo-admin-state" role="alert"><p>{toUiError(query.error).userMessage}</p><button onClick={() => void query.refetch()}>Tentar novamente</button></div>}{query.data?.data.length === 0 && <div className="amigo-admin-state"><h2>Nenhum orçamento encontrado</h2><p>Ajuste os filtros ou crie o primeiro orçamento.</p><button onClick={() => update({ create: '1' })}>Criar primeiro orçamento</button></div>}{query.data && query.data.data.length > 0 && <div className="amigo-admin-table-wrap"><table className="amigo-admin-table"><caption className="amigo-visually-hidden">Orçamentos encontrados</caption><thead><tr><th>Cliente</th><th>Serviço</th><th>Status</th><th>Subtotal</th><th>Desconto</th><th>Total</th><th>Pago</th><th>Saldo</th><th>Situação</th><th>Validade</th><th>Criado em</th><th>Ações</th></tr></thead><tbody>{query.data.data.map((quote) => <tr key={quote.id}><td data-label="Cliente">{quote.serviceRequest.customer.name}</td><td data-label="Serviço">{quote.serviceRequest.service.name}</td><td data-label="Status"><QuoteStatusBadge status={quote.status} /></td><td data-label="Subtotal">{centsToCurrency(quote.subtotalCents)}</td><td data-label="Desconto">{centsToCurrency(quote.discountCents)}</td><td data-label="Total">{centsToCurrency(quote.totalCents)}</td><td data-label="Pago">{centsToCurrency(quote.paidTotalCents)}</td><td data-label="Saldo">{centsToCurrency(quote.remainingCents)}</td><td data-label="Situação">{paymentSituation[quote.paymentStatus]}</td><td data-label="Validade">{quote.validUntil ? date.format(new Date(quote.validUntil)) : 'Sem validade'}</td><td data-label="Criado em">{date.format(new Date(quote.createdAt))}</td><td data-label="Ações"><button onClick={() => update({ quote: quote.id })}>Ver detalhes</button></td></tr>)}</tbody></table></div>}
      {query.data && query.data.pagination.totalPages > 1 && <nav className="amigo-admin-pagination" aria-label="Paginação de orçamentos"><button disabled={page <= 1 || query.isFetching} onClick={() => update({ page: page - 1 === 1 ? undefined : String(page - 1), quote: undefined })}>Anterior</button><span>Página {page} de {query.data.pagination.totalPages}</span><button disabled={page >= query.data.pagination.totalPages || query.isFetching} onClick={() => update({ page: String(page + 1), quote: undefined })}>Próxima</button></nav>}
    </section>{params.get('create') === '1' && <QuoteCreateDialog onClose={() => update({ create: undefined })} onCreated={(id) => { update({ create: undefined, quote: id }); setSuccess('Orçamento criado com sucesso.') }} />}{selected && <QuoteDetails id={selected} onClose={() => update({ quote: undefined })} />}{success && <p role="status" className="amigo-form-message amigo-form-message-success">{success}</p>}</main>
}
