import { useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'
import { AdminPageMetadata } from '../../../components/AdminPageMetadata'
import { listPosts } from '../api/content-api'
import type { ContentType, PostStatus } from '../types/contracts'
const statuses: PostStatus[] = ['DRAFT', 'IN_REVIEW', 'PUBLISHED', 'ARCHIVED']
const types: ContentType[] = ['ARTICLE', 'GUIDE', 'CASE_STUDY', 'BEFORE_AFTER', 'LOCAL_PAGE']
export function AdminContentPage() {
  const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get('page')) || 1); const search = params.get('search') ?? ''; const rawStatus = params.get('status'); const status = statuses.find((item) => item === rawStatus); const rawType = params.get('type'); const contentType = types.find((item) => item === rawType)
  const filters = { page, limit: 20, ...(search ? { search } : {}), ...(status ? { status } : {}), ...(contentType ? { contentType } : {}) }; const query = useQuery({ queryKey: ['content', 'posts', filters], queryFn: ({ signal }) => listPosts(filters, signal) })
  function change(key: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== 'page') next.delete('page'); setParams(next) }
  return <main id="conteudo-principal" className="amigo-admin-page amigo-admin-requests-page"><AdminPageMetadata title="Conteúdos — Amigo do Lar" /><header className="amigo-admin-header"><div><p className="amigo-eyebrow">CMS interno</p><h1>Conteúdos</h1></div><Link className="amigo-button" to="/admin/conteudos/novo">Novo conteúdo</Link></header><section className="amigo-admin-card"><form className="amigo-admin-filters" onSubmit={(event) => event.preventDefault()}><label>Busca<input value={search} onChange={(event) => change('search', event.target.value)} /></label><label>Status<select value={status ?? ''} onChange={(event) => change('status', event.target.value)}><option value="">Todos</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label>Tipo<select value={contentType ?? ''} onChange={(event) => change('type', event.target.value)}><option value="">Todos</option>{types.map((item) => <option key={item}>{item}</option>)}</select></label></form>{query.isLoading && <p role="status">Carregando conteúdos…</p>}{query.isError && <div role="alert" className="amigo-admin-state"><p>Não foi possível carregar os conteúdos.</p><button type="button" onClick={() => void query.refetch()}>Tentar novamente</button></div>}{query.data?.data.length === 0 && <div className="amigo-admin-state"><h2>Nenhum conteúdo encontrado</h2></div>}{query.data && query.data.data.length > 0 && <div className="amigo-admin-table-wrap"><table className="amigo-admin-table"><thead><tr><th>Título</th><th>Status</th><th>Tipo</th><th>Autor</th><th>Atualizado</th><th>Ação</th></tr></thead><tbody>{query.data.data.map((post) => <tr key={post.id}><td>{post.title}</td><td><span className="amigo-admin-badge">{post.status}</span></td><td>{post.contentType}</td><td>{post.author.name}</td><td>{new Date(post.updatedAt).toLocaleDateString('pt-BR')}</td><td><Link to={`/admin/conteudos/${post.id}`}>Editar</Link></td></tr>)}</tbody></table></div>}{query.data && query.data.pagination.totalPages > 1 && <nav aria-label="Paginação"><button disabled={page === 1} onClick={() => change('page', String(page - 1))}>Anterior</button><span> Página {page} de {query.data.pagination.totalPages} </span><button disabled={page >= query.data.pagination.totalPages} onClick={() => change('page', String(page + 1))}>Próxima</button></nav>}</section></main>
}
